global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['api-gateway:8000']
  - job_name: 'product'
    static_configs:
      - targets: ['product-service:8000']
  - job_name: 'auth'
    static_configs:
      - targets: ['auth-service:8000']
  - job_name: 'order'
    static_configs:
      - targets: ['order-service:8000']
  - job_name: 'cart'
    static_configs:
      - targets: ['cart-service:8000']
  - job_name: 'payment'
    static_configs:
      - targets: ['payment-service:8000']
  - job_name: 'log'
    static_configs:
      - targets: ['log-service:8000']
